### PR TITLE
Update to Lightning 3.3.0

### PR DESCRIPTION
**Pull request by hussainweb**
This is the command I ran:

```bash
composer require --update-with-all-dependencies acquia/lightning:3.3.0
```

### CODE REVIEW

**Comment by balsama** [comment]
Thanks. Will make this release today now that Lightning 3.3.0 is out.

**Comment by balsama** [comment]
Looking at some failures in the build now. Will release Headless Lightning 1.5.0-beta1 once we work through those. Possibly as late as tomorrow (3 May).

**Comment by cmcintosh** [comment]
Its now 9/23/2019, any updates?

**Comment by balsama** [comment]
1.5.0-beta1 was tagged in July. This is outdated.
https://packagist.org/packages/acquia/headless_lightning#1.5.0-beta1

**Pull request closed without merging**
